export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAILED = 'GET_STATES_FAILED';

export const GET_FEATURED_PROPERTIES_SUCCESS =
  'GET_FEATURED_PROPERTIES_SUCCESS';
export const GET_FEATURED_PROPERTIES_FAILED = 'GET_FEATURED_PROPERTIES_FAILED';
export const GET_NEW_SALE_PROPERTIES_SUCCESS =
  'GET_NEW_SALE_PROPERTIES_SUCCESS';
export const GET_NEW_SALE_PROPERTIES_FAILED = 'GET_NEW_SALE_PROPERTIES_FAILED';
export const GET_NEW_RENTS_PROPERTIES_SUCCESS =
  'GET_NEW_RENTS_PROPERTIES_SUCCESS';
export const GET_NEW_RENTS_PROPERTIES_FAILED =
  'GET_NEW_RENTS_PROPERTIES_FAILED';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const GET_MY_PROPERTIES_SUCCESS = 'GET_MY_PROPERTIES_SUCCESS';
export const GET_MY_PROPERTIES_FAILED = 'GET_MY_PROPERTIES_FAILED';
