export const REGISTER_USER_SUCCESS = 'REGISTER_USER_SUCCESS';
export const REGISTER_USER_FAILED = 'REGISTER_USER_FAILED';
export const LOGIN_USER_SUCCESS = 'LOGIN_USER_SUCCESS';
export const LOGIN_USER_FAILED = 'LOGIN_USER_FAILED';

export const GET_STATES_SUCCESS = 'GET_STATES_SUCCESS';
export const GET_STATES_FAILED = 'GET_STATES_FAILED';

export const GET_FEATURED_PROPERTIES_SUCCESS =
  'GET_FEATURED_PROPERTIES_SUCCESS';
export const GET_FEATURED_PROPERTIES_FAILED = 'GET_FEATURED_PROPERTIES_FAILED';
export const GET_FEATURED_PROPERTIES_SALES_SUCCESS =
  'GET_FEATURED_PROPERTIES_SALES_SUCCESS';
export const GET_FEATURED_PROPERTIES_SALES_FAILED =
  'GET_FEATURED_PROPERTIES_SALES_FAILED';
export const GET_FEATURED_PROPERTIES_RENTS_SUCCESS =
  'GET_FEATURED_PROPERTIES_RENTS_SUCCESS';
export const GET_FEATURED_PROPERTIES_RENTS_FAILED =
  'GET_FEATURED_PROPERTIES_RENTS_FAILED';

export const GET_NEW_SALE_PROPERTIES_SUCCESS =
  'GET_NEW_SALE_PROPERTIES_SUCCESS';
export const GET_NEW_SALE_PROPERTIES_FAILED = 'GET_NEW_SALE_PROPERTIES_FAILED';
export const GET_NEW_RENTS_PROPERTIES_SUCCESS =
  'GET_NEW_RENTS_PROPERTIES_SUCCESS';
export const GET_NEW_RENTS_PROPERTIES_FAILED =
  'GET_NEW_RENTS_PROPERTIES_FAILED';

export const GET_PROFILE_SUCCESS = 'GET_PROFILE_SUCCESS';
export const GET_PROFILE_FAILED = 'GET_PROFILE_FAILED';
export const GET_MY_PROPERTIES_SUCCESS = 'GET_MY_PROPERTIES_SUCCESS';
export const GET_MY_PROPERTIES_FAILED = 'GET_MY_PROPERTIES_FAILED';
export const GET_MY_WISHLIST_SUCCESS = 'GET_MY_WISHLIST_SUCCESS';
export const GET_MY_WISHLIST_FAILED = 'GET_MY_WISHLIST_FAILED';

export const RESET_PASSWORD_REQUEST_SUCCESS = 'RESET_PASSWORD_REQUEST_SUCCESS';
export const RESET_PASSWORD_REQUEST_FAILED = 'RESET_PASSWORD_REQUEST_FAILED';
export const RESET_PASSWORD_COMMIT_SUCCESS = 'RESET_PASSWORD_COMMIT_SUCCESS';
export const RESET_PASSWORD_COMMIT_FAILED = 'RESET_PASSWORD_COMMIT_FAILED';

export const SEARCH_RESULTS_SUCCESS = 'SEARCH_RESULTS_SUCCESS';
export const SEARCH_RESULTS_FAILED = 'SEARCH_RESULTS_FAILED';

export const FILTER_RESULTS_SUCCESS = 'FILTER_RESULTS_SUCCESS';
export const FILTER_RESULTS_FAILED = 'FILTER_RESULTS_FAILED';

export const EDIT_PROFILE_SUCCESS = 'EDIT_PROFILE_SUCCESS';
export const EDIT_PROFILE_FAILED = 'EDIT_PROFILE_FAILED';

export const CHANGE_NOTIFICATIONS_SUCCESS = 'CHANGE_NOTIFICATIONS_SUCCESS';
export const CHANGE_NOTIFICATIONS_FAILED = 'CHANGE_NOTIFICATIONS_FAILED';
