import { StyleSheet } from 'react-native';
import { spaces } from '../../style/variables';

export default StyleSheet.create({
  safeArea: {
    backgroundColor: '#000',
  },
  container: {
    backgroundColor: '#131516',
    height: 55,
    alignItems: 'center',
    flexDirection: 'row',
  },
  backButton: {
    paddingLeft: spaces.appSpacing01,
    paddingRight: 20,
    marginRight: 10,
    height: '100%',
    alignSelf: 'center',
  },
  homeButtonIcon: {
    color: '#fff',
    fontSize: 30,
  },
  homeButton: {
    paddingRight: 20,
    height: '100%',
    paddingLeft: spaces.appSpacing01,
    marginRight: 10,
    justifyContent: 'center',
  },
  searchButton: {
    height: '100%',
    justifyContent: 'center',
    backgroundColor: '#131516',
  },
  closeButton: {
    paddingRight: 10,
    height: '100%',
    paddingLeft: 5,
    marginRight: 10,
    justifyContent: 'center',
    backgroundColor: '#131516',
  },
  title: {
    color: '#fff',
    fontSize: 20,
    fontFamily: 'Roboto-Medium',
    flex: 1,
  },
  rightButton: {
    minWidth: 20,
    height: '100%',
    justifyContent: 'center',
    alignItems: 'center',
    width: 50,
  },
  icon: {
    color: 'white',
    fontSize: 30,
  },
  searchContainer: {
    backgroundColor: '#131516',
    flex: 1,
    marginHorizontal: spaces.appSpacing01,
    height: 45,
    borderRadius: 6,
    flexDirection: 'row',
  },
  searchInput: {
    flex: 1,
    fontFamily: 'Roboto',
    color: '#fff',
    backgroundColor: '#131516',
    paddingLeft: 15,
    fontWeight: '500',
    fontSize: 18,
  },
  placeholder: {},
  searchResultContainer: {
    zIndex: 100,
    height: 380,
    backgroundColor: '#fff',
  },
  searchResult: {
    backgroundColor: '#ffffff',
    position: 'absolute',
    width: '100%',
    zIndex: 10,
    shadowRadius: 7,
    shadowOffset: { width: 0, height: 1 },
    shadowColor: 'black',
    shadowOpacity: 0.6,
    position: 'absolute',
    top: 0,
    left: 0,
  },
  searchResultItem: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingTop: 16,
    paddingBottom: 16,
    paddingLeft: 20,
    borderColor: 'rgba(19, 21, 22, 0.2)',
    borderBottomWidth: 1,
  },
  emptySearch: {
    backgroundColor: '#fff',
    justifyContent: 'center',
    alignItems: 'center',
    height: 400,
    width: '100%',
    paddingLeft: 20,
    paddingRight: 20,
  },
  emptySearchWrapper: {
    backgroundColor: '#fff',
    height: 800,
    alignItems: 'center',
  },
  emptySearchText: {
    textAlign: 'center',
    color: 'rgba(19, 21, 22, 0.6)',
    fontSize: 16,
    fontWeight: '500',
  },
  item: {
    marginRight: 20,
    backgroundColor: '#fff',
    padding: 10,
    borderRadius: 10,

    shadowColor: '#000',
    shadowOffset: {
      width: 4,
      height: 4,
    },
    shadowOpacity: 0.32,
    shadowRadius: 5.46,
    elevation: 6,
  },
  searchLoader: {
    marginVertical: 30,
  },
  itemText: {
    color: 'rgba(19, 21, 22, 0.7)',
  },
});
